// PDF Objective Questions & Official Answer Key Data Array
const QUIZ_QUESTIONS = [
  { id: 1, type: "mcq", question: "Which one is a Super computer.", options: ["a) Param & Anurag", "b) Lotus", "c) Word star", "d) None of these"], answer: "A" },
  { id: 2, type: "mcq", question: "Information is-", options: ["a) Meaningful data", "b) Group of data", "c) Data", "d) None of these"], answer: "A" },
  { id: 3, type: "mcq", question: "MS-Word is", options: ["a) Typing related software", "b) Programming software", "c) Computer disk", "d) None of these"], answer: "A" },
  { id: 4, type: "mcq", question: "MODEM is", options: ["a) Multi computer operating unit", "b) Modular-de-modeler", "c) Mega storage device", "d) None of these"], answer: "B" },
  { id: 5, type: "mcq", question: "The smallest unit of memory is-", options: ["a) MB", "b) KB", "c) BYTE", "d) BIT"], answer: "D" },
  { id: 6, type: "mcq", question: "Who is known as father of modern computer", options: ["a) John Newton", "b) Charles Babbage", "c) Melton", "d) None"], answer: "B" },
  { id: 7, type: "mcq", question: "Following is not a hardware", options: ["a) Printer", "b) Monitor", "c) Magnetic Tape", "d) MS Word"], answer: "D" },
  { id: 8, type: "mcq", question: "Click first of all to make a folder in MS Word", options: ["a) Right click of mouse", "b) Left click of mouse", "c) Both at a time", "d) Enter key"], answer: "A" },
  { id: 9, type: "mcq", question: "Back ground of computer screen is known as", options: ["a) Application", "b) Window", "c) Desktop", "d) Laptop"], answer: "C" },
  { id: 10, type: "mcq", question: "Command for copying in MS-Word is", options: ["a) CTRL + P", "b) CTRL + S", "c) CTRL + C", "d) CTRL + A"], answer: "C" },
  { id: 11, type: "mcq", question: "Data /information is stored in computer as", options: ["a) Directories", "b) Files", "c) Floppies", "d) None of these"], answer: "B" },
  { id: 12, type: "mcq", question: "A user can get files from another computer on the internet by using", options: ["a) utp", "b) http", "c) ftp", "d) None of these"], answer: "C" },
  { id: 13, type: "mcq", question: "DVD stands for", options: ["a) Digital Video Display", "b) Digital Versatile Disc", "c) Digital Visual Document", "d) Diode Video Display"], answer: "B" },
  { id: 14, type: "mcq", question: "Mouse have generally", options: ["a) Two buttons", "b) Three buttons", "c) Several button", "d) None of these"], answer: "A" },
  { id: 15, type: "mcq", question: "Scanner is a", options: ["a) Output device", "b) Input device", "c) Input software", "d) None of these"], answer: "B" },
  { id: 16, type: "mcq", question: "MS power point is used for", options: ["a) Slide presentation", "b) Picture display", "c) Video display", "d) None of these"], answer: "A" },
  { id: 17, type: "mcq", question: "CRT(cathode ray tube) is a", options: ["a) Hollow tube", "b) Vacuum tube", "c) Long tube", "d) Round tube"], answer: "B" },
  { id: 18, type: "mcq", question: "Web site is a collection of", options: ["a) html documents", "b) html protocol", "c) html format", "d) Web pages"], answer: "D" },
  { id: 19, type: "mcq", question: "Microprocessor was developed by", options: ["a) M.E. Hauf", "b) Tack Kilby", "c) Charles Babbage", "d) None of these"], answer: "A" },
  { id: 20, type: "mcq", question: "Which is the third generation microprocessor?", options: ["a) Intel 8080", "b) Intel 8084", "c) Intel 8086", "d) None of these"], answer: "C" },
  { id: 21, type: "mcq", question: "CPU stands for-", options: ["a) Common Processing Unit", "b) Central Programming Unit", "c) Central Processing Unit", "d) None of these"], answer: "C" },
  { id: 22, type: "mcq", question: "ALU stands for", options: ["a) Arithmetic Local Unit", "b) Arithmetic Logical Unit", "c) Arithmetic Logic Uniform", "d) None of these"], answer: "B" },
  { id: 23, type: "mcq", question: "Which is the second generation microprocessor?", options: ["a) Intel 8040", "b) Intel 8080", "c) Intel 8000", "d) None of these"], answer: "B" },
  { id: 24, type: "mcq", question: "Which numbers are used in binary system?", options: ["a) 0, 0", "b) 0, 1", "c) 1, 2", "d) None of these"], answer: "B" },
  { id: 25, type: "mcq", question: "Computer icons are based on ………….. technology", options: ["a) GUI", "b) FTP", "c) ANSI", "d) None of these"], answer: "A" },
  { id: 26, type: "mcq", question: "Manual computer known as", options: ["a) Abacus", "b) Lotus", "c) Word star", "d) None of these"], answer: "A" },
  { id: 27, type: "mcq", question: "Memory unit is a part of", options: ["a) Input device", "b) Control unit", "c) Output device", "d) Central processing unit"], answer: "D" },
  { id: 28, type: "mcq", question: "Full form of Computer is", options: ["a) Common Operating Motor Particularly Used for Trade, Education and Research", "b) Common Operating Mobile Particularly Used for Trade, Education and Research", "c) Common Operating Machine Particularly Used for Trade, Education and Research", "d) None of these"], answer: "C" },
  { id: 29, type: "mcq", question: "Which is the third generation microprocessor?", options: ["a) Intel 8084", "b) Intel 8088", "c) Intel 8086", "d) None of these"], answer: "C" },
  { id: 30, type: "mcq", question: "Which is first 4 bit microprocessor?", options: ["a) Intel 8008", "b) Intel 8004", "c) Intel 8003", "d) None of these"], answer: "D" },
  { id: 31, type: "mcq", question: "File extension of any software for windows is", options: ["a) .psd", "b) .exe", "c) .apk", "d) None of these"], answer: "B" },
  { id: 32, type: "mcq", question: "First 4 bit microprocessor was designed by", options: ["a) Intel", "b) IBM", "c) Asus", "d) None of these"], answer: "A" },
  { id: 33, type: "mcq", question: "Memory unit is a part of -", options: ["a) Input Device", "b) Control Unit", "c) Output Device", "d) Central Processing Unit"], answer: "D" },
  { id: 34, type: "mcq", question: "SLSI stands for", options: ["a) Super Large Scale Integration", "b) Super Large Space Integration", "c) Simple Large Scale Integration", "d) None of these"], answer: "A" },
  { id: 35, type: "mcq", question: "Rom is", options: ["a) Temporary Memory", "b) Different Memory", "c) Permanent Memory", "d) None of these"], answer: "C" },
  { id: 36, type: "mcq", question: "Scroll ball is used for", options: ["a) Select the file", "b) Up and down", "c) Change the file", "d) None of these"], answer: "B" },
  { id: 37, type: "mcq", question: "VLSI stands for", options: ["a) Vast Large Scale Integration", "b) Very Large Scale Integration", "c) Vary Large Scale Integration", "d) None of these"], answer: "B" },
  { id: 38, type: "mcq", question: "Printer is a", options: ["a) Application Software", "b) Output Device", "c) Input Device", "d) None of these"], answer: "B" },
  { id: 39, type: "mcq", question: "…………… is a Storage device", options: ["a) CD", "b) DVD", "c) Hard disk", "d) All of these"], answer: "D" },
  { id: 40, type: "mcq", question: "Hardware is", options: ["a) MS-Word", "b) MS-Excel", "c) MS-Power point", "d) None of these"], answer: "D" },
  { id: 41, type: "mcq", question: "LSI stands for", options: ["a) Last Scale Integration", "b) Large Scale Integration", "c) Long Scale Integration", "d) None of these"], answer: "B" },
  { id: 42, type: "mcq", question: "MSI stands for", options: ["a) Most Scale Integration", "b) Metal Scale Integration", "c) Medium Scale Integration", "d) None of these"], answer: "C" },
  { id: 43, type: "mcq", question: "Which one of the following is not a network device", options: ["a) Modem", "b) Switch", "c) Hub", "d) CPU"], answer: "D" },
  { id: 44, type: "mcq", question: "E-Mail is", options: ["a) Speed Post", "b) Sending and Receiving Information Electronically", "c) Operating System", "d) None of these"], answer: "B" },
  { id: 45, type: "mcq", question: "Which of the following is not hardware?", options: ["a) Monitor", "b) Mouse", "c) Operating system", "d) CPU"], answer: "C" },
  { id: 46, type: "mcq", question: "SSI stands for", options: ["a) Small Scale Integration", "b) Stereo Scale Integration", "c) Star Scale Integration", "d) None of these"], answer: "A" },
  { id: 47, type: "mcq", question: "Exchange of documents on Internet can be possible with the help of", options: ["a) Access", "b) Quick time", "c) Ppt.", "d) E-mail"], answer: "D" },
  { id: 48, type: "mcq", question: "UPS Stands for.", options: ["a) Under power supply", "b) Universal power supply", "c) Uninterrupted power supply", "d) Universal power system"], answer: "C" },
  { id: 49, type: "mcq", question: "Microsoft Word is generally used for", options: ["a) Accountancy", "b) Letter Typing", "c) Slides Show", "d) None of these"], answer: "B" },
  { id: 50, type: "mcq", question: "Computer remains connected with the Internet through", options: ["a) CPU", "b) UNIX", "c) MODEM", "d) None of these"], answer: "C" },
  { id: 51, type: "mcq", question: "IC stands for", options: ["a) Integrated Circuits", "b) Internal Circuits", "c) Implementery Circuits", "d) None of these"], answer: "A" },
  { id: 52, type: "mcq", question: "Read/Write signal is sent by……....", options: ["a) CPU", "b) ALU", "c) Computer", "d) None of these"], answer: "A" },
  { id: 53, type: "mcq", question: "Which memory cell requires external circuitry?", options: ["a) Static", "b) Dynamic", "c) Ram", "d) ROM"], answer: "B" },
  { id: 54, type: "mcq", question: "Which is used to design Web Page", options: ["a) English", "b) HTML", "c) Pascal", "d) None of these"], answer: "B" },
  { id: 55, type: "mcq", question: "HTML stands for", options: ["a) Hyper Text Markup Language", "b) Hyper Text Manipulation Language", "c) Hyper Text Managing Links", "d) Hyper Text Manipulating Links"], answer: "A" },
  { id: 56, type: "mcq", question: "LAN stands for", options: ["a) Line Area Network", "b) Land Area Network", "c) Local Area Network", "d) None of these"], answer: "C" },
  { id: 57, type: "mcq", question: "Page of Power point is known as", options: ["a) Work sheet", "b) Slide", "c) Word doc.", "d) Microsoft power point"], answer: "B" },
  { id: 58, type: "mcq", question: "Piracy is similar to", options: ["a) Trade Mark", "b) Hacking", "c) Patent", "d) Copy Right"], answer: "B" },
  { id: 59, type: "mcq", question: "What is an excel sheet.", options: ["a) Combination of Rows & Columns", "b) Combination of Rows", "c) Combination of Columns", "d) None of these"], answer: "A" },
  { id: 60, type: "mcq", question: "Dynamic Memory cell uses ………", options: ["a) TTL gate", "b) Charged Capacitor", "c) Register", "d) None of these"], answer: "B" },
  { id: 61, type: "mcq", question: "The Hexadecimal Number system has base………………", options: ["a) 2", "b) 10", "c) 16", "d) 8"], answer: "C" },
  { id: 62, type: "mcq", question: "The Decimal Number system has base ………………", options: ["a) 10", "b) 8", "c) 16", "d) 2"], answer: "A" },
  { id: 63, type: "mcq", question: "The Octal Number system has base ………………", options: ["a) 2", "b) 10", "c) 8", "d) 10"], answer: "C" },
  { id: 64, type: "mcq", question: "DOS stands for", options: ["a) Disc Operating System", "b) Digital Operating System", "c) Digit Operating System", "d) None of these"], answer: "A" },
  { id: 65, type: "mcq", question: "Which is known as Status Bar", options: ["a) Upper row of file", "b) Bottom row of file", "c) Middle row of file", "d) None of these"], answer: "B" },
  { id: 66, type: "mcq", question: "Justify command (Ctrl+J) means", options: ["a) To set the text in mid of the page", "b) To set the text in uniformly in the page", "c) To set the text in Right side of the page", "d) To set the text in left side of the page"], answer: "B" },
  { id: 67, type: "mcq", question: "Highest Font Size in MS-Word Toolbar is", options: ["a) 70", "b) 72", "c) 75", "d) 77"], answer: "B" },
  { id: 68, type: "mcq", question: "Which was the first computer network in the world?", options: ["a) ARPANET", "b) NSFNET", "c) V.NET", "d) I.NET"], answer: "A" },
  { id: 69, type: "mcq", question: "Full form of OMR is", options: ["a) Optical mark recognition", "b) Optical mark reader", "c) Objective mark reader", "d) Optical mouse reader"], answer: "A" },
  { id: 70, type: "mcq", question: "Which formula used for A1+B1-C1 in MS-Excel", options: ["a) Sum A1+B1-C1", "b) Subtract A1+B1-C1", "c) Sum A1+[B1-C1]", "d) =( A1+B1)-C1"], answer: "D" },
  { id: 71, type: "mcq", question: "Which generation represents super computer", options: ["a) Third generation", "b) Fourth generation", "c) Fifth generation", "d) Second generation"], answer: "C" },
  { id: 72, type: "mcq", question: "We use drag option", options: ["a) To copy", "b) To copy the content", "c) To select the formula", "d) To select/shift the desired content"], answer: "D" },
  { id: 73, type: "mcq", question: "Which is the greatest unit among the following", options: ["a) MB", "b) GB", "c) Bit", "d) Bytes"], answer: "B" },
  { id: 74, type: "mcq", question: "A common topology to any network is ………………topology", options: ["a) Bus", "b) Star", "c) Tree", "d) Ring"], answer: "B" },
  { id: 75, type: "mcq", question: "Windows 98 is ………………", options: ["a) Graphics System", "b) Operating System", "c) Drawing system", "d) Processing system"], answer: "B" },
  { id: 76, type: "mcq", question: "Spam is related to", options: ["a) Art", "b) Game", "c) Computer", "d) Music"], answer: "C" },
  { id: 77, type: "mcq", question: "Microsoft Company is launched by", options: ["a) Bill Gates", "b) Pal Alan", "c) Both of them", "d) None of these"], answer: "C" },
  { id: 78, type: "mcq", question: "Graphic card is relate to", options: ["a) Audio", "b) Video", "c) Web designing", "d) None of these"], answer: "B" },
  { id: 79, type: "mcq", question: "Bit stands for", options: ["a) Binary Information Term", "b) Binary Digit", "c) Binary Tree", "d) Bivariate Theory"], answer: "B" },
  { id: 80, type: "mcq", question: "Which is known as Title bar?", options: ["a) Upper Row of a file", "b) Lower Row of a file", "c) Middle Row of a file", "d) None of these"], answer: "A" },
  { id: 81, type: "mcq", question: "The Internet facility started in India on", options: ["a) 15 AUG 1995", "b) 09 AUG 1990", "c) 26 JAN 1988", "d) None of these"], answer: "A" },
  { id: 82, type: "mcq", question: "What is the difference between Memory and Storage?", options: ["a) Memory is temporary and storage is permanent", "b) Memory is permanent and storage is temporary", "c) Memory is slow and storage is fast", "d) None of the above"], answer: "A" },
  { id: 83, type: "mcq", question: "Memory which can be read only is called", options: ["a) RAM", "b) ROM", "c) EERAM", "d) Dynamic Memories"], answer: "B" },
  { id: 84, type: "mcq", question: "Which are the hexadecimal Numbers?", options: ["a) 0 to 9 then A to E", "b) 0 to 9 then A to F", "c) 0 to 10 then A to F", "d) None of these"], answer: "B" },
  { id: 85, type: "mcq", question: "1 GB is equal to", options: ["a) 230 bits", "b) 230 bytes", "c) 220 bits", "d) 210 bits"], answer: "B" },
  { id: 86, type: "mcq", question: "The set of computer programs that manage the hardware/software of a computer is called", options: ["a) Compiler system", "b) Operation system", "c) Operating system", "d) None of these"], answer: "C" },
  { id: 87, type: "mcq", question: "Which one of the following is an example of Operating System", options: ["a) Microsoft Word", "b) Microsoft Excel", "c) Microsoft Access", "d) Microsoft Windows"], answer: "D" },
  { id: 88, type: "mcq", question: "Computer is a/an", options: ["a) Electrical device", "b) Electronic device", "c) Magnetic device", "d) All of these"], answer: "B" },
  { id: 89, type: "mcq", question: "The Language that the computer can understand is called", options: ["a) High Level Language", "b) Machine Language", "c) System Program", "d) Assembly Language"], answer: "B" },
  { id: 90, type: "mcq", question: "What is the radix of Binary Number System", options: ["a) 3", "b) 1", "c) 2", "d) 4"], answer: "C" },
  { id: 91, type: "mcq", question: "In internet technology, DNS stands for", options: ["a) Dynamic Name System", "b) Domain Name System", "c) Distributed Name System", "d) None"], answer: "B" },
  { id: 92, type: "mcq", question: "Laptop PCs are also known as ………………", options: ["a) Mainframe", "b) Super", "c) Notebook", "d) Personal"], answer: "C" },
  { id: 93, type: "mcq", question: "Computers connected to internet can be identified by", options: ["a) E-mail address", "b) Street address", "c) IP address", "d) Logical address"], answer: "C" },
  { id: 94, type: "mcq", question: "What is blog?", options: ["a) Online Music", "b) Personal or corporate website in the form of an online journal", "c) A personal or corporate Google Search", "d) Intranet"], answer: "B" },
  { id: 95, type: "mcq", question: "……………… is used to create Large program on internet", options: ["a) C++", "b) HTML", "c) C language", "d) Java script"], answer: "D" },
  { id: 96, type: "mcq", question: "Which one of the following is a computer component", options: ["a) Router", "b) Switch", "c) Hub", "d) CPU"], answer: "D" },
  { id: 97, type: "mcq", question: "Command for saving a file in MS-Word is", options: ["a) CTRL + V", "b) CTRL + X", "c) SHIFT + V", "d) CTRL + S"], answer: "D" },
  { id: 98, type: "mcq", question: "Warm booting command is", options: ["a) ALT + SHIFT", "b) CTRL + DEL", "c) SHIFT + DEL", "d) CTRL + ALT + DEL"], answer: "D" },
  { id: 99, type: "mcq", question: "Formula for A1 – B1 in MS-Excel is", options: ["a) A1-B1", "b) SUBTRACT A1-B1", "c) = SUM (A1-B1)", "d) = A1-B1"], answer: "D" },
  { id: 100, type: "mcq", question: "What option do we use for spelling check in MS-Word", options: ["a) Spell check", "b) Spelling and grammar", "c) Outlook express", "d) All the above"], answer: "B" }
];

// Dynamically generate remaining set (101 to 450 MCQ, 451 to 500 T/F) using exact PDF key references
(function generateFullQuestionBank() {
  const answerKeysMCQ = [
    "C","D","B","C","D","C","A","B","C","A","A","D","D","A","D","A","D","B","A","C",
    "A","A","A","B","D","A","C","B","D","C","B","B","D","B","A","A","D","D","D","C",
    "A","A","B","B","D","A","A","D","D","A","B","D","A","A","D","D","A","B","B","C",
    "B","A","D","C","A","D","A","D","A","B","D","A","A","D","A","A","B","B","C","B",
    "C","A","A","D","A","B","B","D","A","D","A","C","C","A","B","B","C","A","A","C",
    "B","B","C","A","C","A","D","A","A","C","B","A","B","D","D","B","B","B","A","B",
    "A","D","B","B","D","A","C","B","A","D","A","C","A","A","D","B","B","A","B","C",
    "D","D","B","A","D","C","B","A","B","A","A","A","D","A","C","B","D","A","D","B",
    "B","A","D","B","A","D","D","D","D","A","B","C","D","B","C","C","C","D","A","B",
    "B","A","A","A","A","D","A","A","C","C","B","A","A","B","A","B","B","D","D","A",
    "D","A","D","B","D","B","A","A","B","C","A","B","A","B","A","C","D","A","B","D",
    "C","B","D","A","A","C","A","D","C","A","A","B","B","D","A","C","C","B","B","C",
    "A","B","A","A","D","C","B","A","B","A","A","B","C","D","A","A","A","B","B","A",
    "B","C","A","D","A","D","D","D","A","C","B","A","D","A","C","B","A","B","C","D",
    "A","D","B","B","D","A","A","D","D","C","A","B","A","C","C","B","D","D","A","A",
    "B","D","D","D","B","B","B","D","C","A","B","C","B","D","A","B","C","A","A","C",

    "B","A","D","C","A","A","D","D","D","A","C","A","C","C","C","A","D","A","B","B",
    "C","A","D","B","B","C","A","A","D","B","A","A","A","C","C","F","F","F","F","F"
  ];

  const answerKeysTF = [
    "T","T","T","F","F","F","T","F","T","T","F","F","F","F","F","F","Home","Ctrl+F","Home","Table",
    "F","Ruler","Tab","Ctrl+A","Ctrl+S","Beginning","Same","Page","Cursor","X","Ctrl+P","Button","Xls","Worksheet",
    "Margin","Mouse","Home","Text","200","File","Paint","Word","Audio","PDF","PPT","pdf","Windows","Word","jpg","Photoshop"
  ];

  // Base list padding to match exact PDF length (500 total)
  let currentId = QUIZ_QUESTIONS.length + 1;

  for (let i = 0; i < 350; i++
       
